"""
Standard Data Schemas for Antigravity CV-Sec Auditing Framework.
Provides consistent reporting structures across all 5 modules.
"""

from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import List, Dict, Any, Optional
import json
import time


class SeverityLevel(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ModuleType(str, Enum):
    DATA_INTEGRITY = "DATA_INTEGRITY"
    MODEL_INTEGRITY = "MODEL_INTEGRITY"
    CRYPTO_PROVENANCE = "CRYPTO_PROVENANCE"
    DRIFT_DETECTION = "DRIFT_DETECTION"
    SYSTEM = "SYSTEM"


@dataclass
class FlagReport:
    """Standardized issue/anomaly report generated by any audit module."""
    module: ModuleType
    severity: SeverityLevel
    title: str
    description: str
    target_item: str  # File path, model layer name, sample index, etc.
    metrics: Dict[str, Any] = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data['module'] = self.module.value if isinstance(self.module, ModuleType) else self.module
        data['severity'] = self.severity.value if isinstance(self.severity, SeverityLevel) else self.severity
        return data


@dataclass
class InspectionResult:
    """Overall summary result for a completed audit run."""
    module: ModuleType
    status: str  # "PASSED", "WARNING", "FAILED"
    total_inspected: int
    flags_count: int
    flags: List[FlagReport] = field(default_factory=list)
    risk_score: float = 0.0  # Normalized 0.0 to 100.0
    summary: str = ""
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "module": self.module.value if isinstance(self.module, ModuleType) else self.module,
            "status": self.status,
            "total_inspected": self.total_inspected,
            "flags_count": self.flags_count,
            "flags": [f.to_dict() if isinstance(f, FlagReport) else f for f in self.flags],
            "risk_score": self.risk_score,
            "summary": self.summary,
            "timestamp": self.timestamp
        }
